### ISSUE TITLE
ros-noetic-gazebo-ros error when building

### ISSUE THREAD

**Issue by kixune21** [ros-noetic-arch/ros-noetic-gazebo-ros#3]
Hi! While I was building this particular package on Arch Linux (using yay or makepkg results in the same errors) some recurrent error about  "Protocol Buffer headers"  occured.
I generated this [log file](https://bin.smwcentral.net/u/29129/ros-noetic-gazebo-ros-2.9.1-1-x86_64-build.log)  in case it helps to find a solution.

**Comment by acxz** [comment]
Seems like we need to rebuild the packages on your system, since it is looking for an older protobuf, but protobuf has been updated.
Can you try a `yay -Syu ros-noetic-desktop-full --rebuildtree` and make sure to press `A` when prompted to clean rebuild?
See https://github.com/ros-noetic-arch/ros-noetic-desktop-full/issues/10#issuecomment-653168991

**Comment by kixune21** [comment]
Thanks! Everything installed correctly after adding the --rebuildtree option.
