### ISSUE TITLE
HiDPI issues

### ISSUE THREAD

**Issue by WysokiStudent** [ros-noetic-arch/ros-noetic-gazebo-ros#4]
It seems that gazebo is not too friendly with high DPI displays. Only the upper left part of the view shows the scene, the rest of the view is unrendered garbage. This was noted before in https://github.com/osrf/gazebo/issues/2688.

I can confirm that running gazebo with the following env parameter fixes the issue.
`
QT_SCREEN_SCALE_FACTORS=[1.0]
`
In the comments of the aforementioned issue the proposed solution is to wrap gzclient in a script.

Copy-paste example:
` TURTLEBOT3_MODEL=burger QT_SCREEN_SCALE_FACTORS=[1.0] roslaunch turtlebot3_gazebo turtlebot3_world.launch
`

**Comment by acxz** [comment]
Hey @WysokiStudent thanks for letting us know, but I'm afraid this is an issue on the user end.
I suggest you add this to the [HiDPI ArchWiki](https://wiki.archlinux.org/index.php/HiDPI) article under a section called Gazebo.

SInce your concern is not related to `ros-noetic-gazebo-ros` I'll go ahead and close this issue.
